<a href="https://colab.research.google.com/github/its-Kumar/Deep_Learning/blob/master/1_Artificial_Neural_Networks/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

## Part 1 - Data Preprocessing


### Importing the libraries


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow.keras as keras
tf.__version__

'2.2.0'

### Importing the dataset


In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [3]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### Encoding categorical data



In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct =  ColumnTransformer([('encoder', OneHotEncoder(), [1])],
                        remainder='passthrough')
X = ct.fit_transform(X)
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Splitting the dataset into the Training set and Test set


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=0)

### Feature Scaling


In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Now let's make the ANN!

In [8]:
# Initialising the ANN
classifier = keras.models.Sequential()

In [9]:
# Adding the input layer and the first hidden layer
classifier.add(keras.layers.Dense(units=8,
                                  activation='relu'))

In [10]:
# Adding the second hidden layer
classifier.add(keras.layers.Dense(units=8,
                                  activation='relu'))

In [11]:
# Adding the output layer
classifier.add(keras.layers.Dense(units=1,
                                  activation='sigmoid'))

In [12]:
# Compiling the ANN
classifier.compile(optimizer='adam',
                   loss='binary_crossentropy',
                   metrics = ['accuracy'])

In [13]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train,
               batch_size=25,
               epochs=100)

Epoch 1/100
320/320 [==============================] - 0s 1ms/step - loss: 0.5886 - accuracy: 0.6921
Epoch 2/100
320/320 [==============================] - 0s 1ms/step - loss: 0.4485 - accuracy: 0.8075
Epoch 3/100
320/320 [==============================] - 0s 1ms/step - loss: 0.4194 - accuracy: 0.8152
Epoch 4/100
320/320 [==============================] - 0s 1ms/step - loss: 0.4026 - accuracy: 0.8230
Epoch 5/100
320/320 [==============================] - 0s 1ms/step - loss: 0.3868 - accuracy: 0.8334
Epoch 6/100
320/320 [==============================] - 0s 1ms/step - loss: 0.3717 - accuracy: 0.8451
Epoch 7/100
320/320 [==============================] - 0s 1ms/step - loss: 0.3605 - accuracy: 0.8510
Epoch 8/100
320/320 [==============================] - 0s 1ms/step - loss: 0.3527 - accuracy: 0.8544
Epoch 9/100
320/320 [==============================] - 0s 1ms/step - loss: 0.3482 - accuracy: 0.8555
Epoch 10/100
320/320 [==============================] - 0s 1ms/step - loss: 0.3456 - accura

## Part 3 - Making predictions and evaluating the model


In [14]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_test.reshape(-1,1), y_pred.reshape(-1,1)), axis=1))

[[0 0]
 [1 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### predicting a single new observation

Predict if the customer with the following imformations will 

leave the bank or not??

Geography: France

Credit Score: 600

Gender: Male

Age: 40

Balance: 60000

Number of products: 2

Has credit card: Yes

is Active member: Yes

Estimated Salary: 50000


In [18]:
classifier.predict(sc.transform(
    [[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])
) > 0.5

array([[False]])

In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[1504,   91],
       [ 197,  208]])

In [20]:
accuracy_score(y_test, y_pred)

0.856